# Generated by Django 3.1.6 on 2021-03-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileUpload', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('title', models.CharField(max_length=200)),
                ('EventLink', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('isLatest', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('dateEvent', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('cell', models.CharField(choices=[('Incubation Cell', 'Incubation Cell'), ('Innovation Cell', 'Innovation Cell'), ('Startup Cell', 'Startup Cell'), ('IPR Cell', 'IPR Cell')], max_length=50)),
                ('speakerName', models.CharField(max_length=100)),
                ('googleFormLink', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=100)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
