# Generated by Django 3.1.6 on 2021-03-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210306_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='EventLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
