# Generated by Django 3.1.6 on 2021-03-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_events_eventorganizer1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='contact_no',
            field=models.BigIntegerField(),
        ),
    ]
