# Generated by Django 3.1.6 on 2021-03-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210311_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='Eventorganizer1',
        ),
        migrations.AddField(
            model_name='events',
            name='Eventorganizer1',
            field=models.ManyToManyField(to='home.organizer'),
        ),
    ]
