# Generated by Django 3.1.6 on 2021-03-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210311_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='Eventorganizer1',
            new_name='Eventorganizers',
        ),
    ]
