# Generated by Django 3.1.6 on 2021-03-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210312_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='person_name',
            new_name='name',
        ),
    ]
