# Generated by Django 3.1.6 on 2021-03-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210312_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinIIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=40)),
                ('college', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
