# Generated by Django 3.1.6 on 2021-06-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210604_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annou',
            name='fileUpload',
        ),
        migrations.AddField(
            model_name='annou',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
