# Generated by Django 3.1.6 on 2021-06-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210604_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iicfaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
