# Generated by Django 3.1.6 on 2021-06-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_homeslider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeSlider',
        ),
    ]
