# Generated by Django 3.1.6 on 2021-06-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_downloadtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadtable',
            name='number',
            field=models.IntegerField(),
        ),
    ]
