# Generated by Django 3.1.6 on 2021-06-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_incubationimage_innovationimage_iprimage_startupimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Annou',
            new_name='Achivements',
        ),
    ]
