# Generated by Django 3.1.6 on 2021-06-26 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20210626_2250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Iicfaculty',
        ),
    ]
