# Generated by Django 3.1.6 on 2021-07-04 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_secratory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('isUploadable', models.BooleanField(default=False)),
            ],
        ),
    ]
