# Generated by Django 3.1.6 on 2021-07-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_cordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cordinator',
            name='role',
            field=models.CharField(choices=[('Ipr Co-ordinator', 'Ipr Co-ordinator'), ('Ipr Member', 'Ipr Member'), ('Innovation Co-ordinator', 'Innovation Co-ordinator'), ('Innovation Member', 'Innovation Member'), ('Startup Co-ordinator', 'Startup Co-ordinator'), ('Startup Member', 'Startup Member'), ('Incubation Co-ordinator', 'Incubation Co-ordinator'), ('Incubation Member', 'Incubation Member'), ('IIC Faculty', 'IIC Faculty'), ('Ipr Students', 'Ipr Students'), ('Innovation Students', 'Innovation Students'), ('Startup Students', 'Startup Students'), ('Incubation Students', 'Incubation Students'), ('Secratory', 'Secratory')], max_length=50),
        ),
    ]
