# Generated by Django 3.1.6 on 2021-07-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20210704_2102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='iicfaculty',
        ),
        migrations.DeleteModel(
            name='Incubationcoordinator',
        ),
        migrations.DeleteModel(
            name='Incubationstudents',
        ),
        migrations.DeleteModel(
            name='Incubationupmember',
        ),
        migrations.DeleteModel(
            name='Innovationcoordinator',
        ),
        migrations.DeleteModel(
            name='Innovationmember',
        ),
        migrations.DeleteModel(
            name='Innovationstudents',
        ),
        migrations.DeleteModel(
            name='Iprcoordinator',
        ),
        migrations.DeleteModel(
            name='Iprmember',
        ),
        migrations.DeleteModel(
            name='Iprstudents',
        ),
        migrations.DeleteModel(
            name='Secratory',
        ),
        migrations.DeleteModel(
            name='Startupcoordinator',
        ),
        migrations.DeleteModel(
            name='Startupmember',
        ),
        migrations.DeleteModel(
            name='Startupstudents',
        ),
    ]
