# Generated by Django 3.1.6 on 2021-07-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20210705_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivements',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Achievement'),
        ),
        migrations.AlterField(
            model_name='cordinator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Cordinator'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(upload_to='images/Events'),
        ),
        migrations.AlterField(
            model_name='experts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Expert'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Slider'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/organizers/'),
        ),
    ]
