# Generated by Django 3.1.6 on 2021-07-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20210706_0828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
