# Generated by Django 3.1.6 on 2021-07-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20210706_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cell',
            field=models.CharField(choices=[('Institution’s Innovation Council (IICs)', 'Institution’s Innovation Council (IICs)'), ('Incubation Cell', 'Incubation Cell'), ('Innovation Cell', 'Innovation Cell'), ('Startup Cell', 'Startup Cell'), ('Ipr Cell', 'Ipr Cell')], max_length=50),
        ),
    ]
