# Generated by Django 3.1.6 on 2021-07-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20210718_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('cell', models.CharField(choices=[('Incubation Cell', 'Incubation Cell'), ('Innovation Cell', 'Innovation Cell'), ('Startup Cell', 'Startup Cell'), ('Ipr Cell', 'Ipr Cell')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/Cell')),
            ],
        ),
    ]
