# Generated by Django 3.1.6 on 2021-07-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_cellinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellinfo',
            name='cell',
            field=models.CharField(choices=[('Incubation Cell', 'Incubation Cell'), ('Innovation Cell', 'Innovation Cell'), ('Startup Cell', 'Startup Cell'), ('IPR Cell', 'IPR Cell')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cordinator',
            name='role',
            field=models.CharField(choices=[('IPR Co-ordinator', 'IPR Co-ordinator'), ('IPR Member', 'IPR Member'), ('Innovation Co-ordinator', 'Innovation Co-ordinator'), ('Innovation Member', 'Innovation Member'), ('Startup Co-ordinator', 'Startup Co-ordinator'), ('Startup Member', 'Startup Member'), ('Incubation Co-ordinator', 'Incubation Co-ordinator'), ('Incubation Member', 'Incubation Member'), ('IIC Faculty', 'IIC Faculty'), ('IPR Students', 'IPR Students'), ('Innovation Students', 'Innovation Students'), ('Startup Students', 'Startup Students'), ('Incubation Students', 'Incubation Students'), ('Secratory', 'Secratory')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='cell',
            field=models.CharField(choices=[('Institution’s Innovation Council (IICs)', 'Institution’s Innovation Council (IICs)'), ('Incubation Cell', 'Incubation Cell'), ('Innovation Cell', 'Innovation Cell'), ('Startup Cell', 'Startup Cell'), ('IPR Cell', 'IPR Cell')], max_length=50),
        ),
    ]
