# Generated by Django 3.1.6 on 2021-07-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20210718_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadtable',
            name='number',
        ),
        migrations.AlterField(
            model_name='downloadtable',
            name='link',
            field=models.URLField(max_length=300),
        ),
    ]
