# Generated by Django 3.1.6 on 2021-07-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20210718_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Eventorganizers',
        ),
        migrations.DeleteModel(
            name='organizer',
        ),
    ]
