# Generated by Django 3.1.6 on 2021-07-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20210718_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('profession', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/Developer')),
                ('facebook_ID', models.URLField()),
                ('instagram_ID', models.URLField()),
                ('linkdin_ID', models.URLField()),
                ('github_ID', models.URLField()),
            ],
        ),
    ]
