# Generated by Django 3.1.6 on 2021-07-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='facebook_ID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='developer',
            name='github_ID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='developer',
            name='instagram_ID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='developer',
            name='linkdin_ID',
            field=models.CharField(max_length=200),
        ),
    ]
