# Generated by Django 3.2.5 on 2021-07-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20210718_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadtable',
            name='createdDate',
        ),
    ]
