# Generated by Django 3.2.5 on 2021-07-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_remove_downloadtable_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cordinator',
            name='role',
            field=models.CharField(choices=[('IPR Co-ordinator', 'IPR Co-ordinator'), ('IPR Member', 'IPR Member'), ('Innovation Co-ordinator', 'Innovation Co-ordinator'), ('Innovation Member', 'Innovation Member'), ('Startup Co-ordinator', 'Startup Co-ordinator'), ('Startup Member', 'Startup Member'), ('Incubation Co-ordinator', 'Incubation Co-ordinator'), ('Incubation Member', 'Incubation Member'), ('IIC Faculty', 'IIC Faculty'), ('IPR Students', 'IPR Students'), ('Innovation Students', 'Innovation Students'), ('Startup Students', 'Startup Students'), ('Incubation Students', 'Incubation Students'), ('Secratary', 'Secratary')], max_length=50),
        ),
    ]
